const express = require('express');
const router = express.Router();

const {Pool} = require('pg')
const db = new Pool({
  database: 'drum_beats',
  password: 'Jimmyhand91',
})

const cloudinary = require('cloudinary').v2

cloudinary.config({ 
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME, 
  api_key: process.env.CLOUDINARY_API_KEY, 
  api_secret: process.env.CLOUDINARY_API_SECRET,
  secure: true
});


db.connect()

router.get('/', (req, res) => {
  db.query('select * from tracks;').then(dbRes => {
    res.json(dbRes.rows)
  })
})

router.post('/', (req, res) => {
  console.log("a file has been sent");
  console.log(req.Headers);



  // cloudinary.uploader.upload('pizza.jpg', { tags: 'basic_sample' }, function (err, image) {
  //   console.log();
  //   console.log("** File Upload");
  //   if (err) { console.warn(err); }
  //   console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
  //   console.log("* " + image.public_id);
  //   console.log("* " + image.url);
  //   waitForAllUploads("pizza", err, image);
  // });

})

module.exports = router